server.port=${PORT:8080}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
spring.mvc.async.request-timeout=-1
agent.token=${AGENT_SERVE_TOKEN:}
info.app.name=agent-server
